# Interval in which signs update in ticks (20ticks = 1second)
sign-update-interval: 60

# The subfolder where commands get loaded from (/ultimatesigns cmd file)
commands-folder: "/commands/"

# Do players need the permission 'ultimatesigns.update' to have signs updated (with color, names etc.)
enable-update-permission: true

# Custom variables. Can be used on signs and in commands (for example: [example])
variables:
  example:
    value: "&aUltimate&1Signs"
